export const OUTPUT_LANGUAGES = [
  { value: 'auto', label: 'Auto-detect (match transcript)' },
  { value: 'English', label: 'English' },
  { value: 'Hebrew', label: 'Hebrew (עברית)' },
  { value: 'Arabic', label: 'Arabic (العربية)' },
  { value: 'Chinese', label: 'Chinese (中文)' },
  { value: 'Czech', label: 'Czech (Čeština)' },
  { value: 'Danish', label: 'Danish (Dansk)' },
  { value: 'Dutch', label: 'Dutch (Nederlands)' },
  { value: 'Finnish', label: 'Finnish (Suomi)' },
  { value: 'French', label: 'French (Français)' },
  { value: 'German', label: 'German (Deutsch)' },
  { value: 'Greek', label: 'Greek (Ελληνικά)' },
  { value: 'Hindi', label: 'Hindi (हिन्दी)' },
  { value: 'Hungarian', label: 'Hungarian (Magyar)' },
  { value: 'Indonesian', label: 'Indonesian (Bahasa Indonesia)' },
  { value: 'Italian', label: 'Italian (Italiano)' },
  { value: 'Japanese', label: 'Japanese (日本語)' },
  { value: 'Korean', label: 'Korean (한국어)' },
  { value: 'Malay', label: 'Malay (Bahasa Melayu)' },
  { value: 'Norwegian', label: 'Norwegian (Norsk)' },
  { value: 'Persian', label: 'Persian (فارسی)' },
  { value: 'Polish', label: 'Polish (Polski)' },
  { value: 'Portuguese', label: 'Portuguese (Português)' },
  { value: 'Romanian', label: 'Romanian (Română)' },
  { value: 'Russian', label: 'Russian (Русский)' },
  { value: 'Spanish', label: 'Spanish (Español)' },
  { value: 'Swedish', label: 'Swedish (Svenska)' },
  { value: 'Thai', label: 'Thai (ไทย)' },
  { value: 'Turkish', label: 'Turkish (Türkçe)' },
  { value: 'Ukrainian', label: 'Ukrainian (Українська)' },
  { value: 'Vietnamese', label: 'Vietnamese (Tiếng Việt)' },
] as const;

export type OutputLanguage = (typeof OUTPUT_LANGUAGES)[number]['value'];
